apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: image-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build/image-controller@sha256:4e7b891f5be8675da7d1846bafd24fa012f9caec6d5198da8437e69d8bffd713
        name: container-image
        resources: {}
status: {}
