apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: image-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build/image-controller@sha256:6a9c0b6eea75a6bf5d3f0f335eaef4dea4d612529c63bc9ec4a6a33c99ad4e7d
        name: container-image
        resources: {}
status: {}
