apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-service
    app.kubernetes.io/part-of: build
  name: build-service
spec:
  ports:
  - port: 776
    targetPort: 776
  selector:
    app.kubernetes.io/instance: build-service
status:
  loadBalancer: {}
